"""Inventory bounded two-instruction forms at initial relocated code-pointer candidates."""
import argparse,bisect,collections,json,sqlite3
from pathlib import Path
from capstone import Cs,CS_ARCH_X86,CS_MODE_64
from tools.cfg_recover_startup import sha,write_json
from tools.formats import ElfImage
p=argparse.ArgumentParser();p.add_argument('probe',type=Path);p.add_argument('out',type=Path);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False);read=lambda p:json.loads(Path(p).read_text(encoding='utf-8'));probe=read(a.probe/'summary.json');assert probe['game_aot_execution'] and not probe['original_byte_cpu_execution'];registry=Path('local/runtime/registry-v7-memory-repeat');assert probe['registry_identity']==sha(registry/'identity.json');module=next(m for m in read(registry/'modules.json') if m['name']=='eboot.bin');assert sha(module['path'])==module['module'];im=ElfImage(Path(module['path']).read_bytes());base=module['logical_base'];segments=[s for s in im.segments if s.type in [1,0x61000010] and s.flags&1];known={r['pc'] for r in read(a.probe/'compilation-targets.json')+read(registry/'imports.json')};locations=collections.defaultdict(list)
for r in im.linkage()['relocations']:
 if r['type']==8 and any(s.vaddr<=r['addend']<s.vaddr+s.filesz for s in segments):locations[r['addend']].append(r)
source=Path('local/cfg/startup-recovery-v31-conditional-repeat/analysis.sqlite');db=sqlite3.connect(source.resolve().as_uri()+'?mode=ro',uri=True);prior=[(at,at+size) for at,size in db.execute('select rva,size from recovery_instruction where module=? order by rva',(module['module'],))]
for o in read(a.probe/'compilation-objects.json')[386:]:
 for i in read(Path(o['path']).parent/'input.json')['instructions']:
  if base<=i['address']<base+0x100000000:prior.append((i['address']-base,i['address']-base+len(bytes.fromhex(i['bytes']))))
prior.sort();starts=[r[0] for r in prior];ranges=list(db.execute('select start,size,confidence from unwind_range where module=? order by start',(module['module'],)));range_starts=[r[0] for r in ranges];md=Cs(CS_ARCH_X86,CS_MODE_64);bodies=[];counts=collections.Counter();excluded=[]
for at in sorted(locations):
 if base+at in known:counts['already_compiled']+=1;continue
 segment=next(s for s in segments if s.vaddr<=at<s.vaddr+s.filesz);raw=im.at_va(at,min(8,segment.vaddr+segment.filesz-at));size=4 if len(raw)>=4 and raw[:2]==bytes.fromhex('8a47') and raw[2]<128 and raw[3]==0xc3 else 5 if len(raw)>=5 and raw[:3]==bytes.fromhex('488b47') and raw[3]<128 and raw[4]==0xc3 else 8 if len(raw)==8 and raw[:3]==bytes.fromhex('488d05') and raw[7]==0xc3 else 0
 if not size:counts['outside_supported_forms']+=1;continue
 start=bisect.bisect_left(starts,at);overlaps=[r for r in prior[max(0,start-1):bisect.bisect_left(starts,at+size)] if r[1]>at]
 if overlaps:counts['overlaps_prior_instructions']+=1;excluded.append(dict(rva=at,overlaps=overlaps));continue
 ins=list(md.disasm(raw[:size],at));assert len(ins)==2 and ins[-1].bytes==b'\xc3' and sum(i.size for i in ins)==size;index=bisect.bisect_right(range_starts,at)-1;unwind=[ranges[index]] if index>=0 and ranges[index][0]+ranges[index][1]>at else [];bodies.append(dict(pc=base+at,rva=at,end=at+size,instructions=[dict(rva=i.address,size=i.size,bytes=i.bytes.hex(),mnemonic=i.mnemonic,operands=i.op_str) for i in ins],initial_pointer_relocations=locations[at],unwind=unwind,observed_requested_entry=False));counts['conditional_supported_candidate']+=1
assert all(a['end']<=b['rva'] for a,b in zip(bodies,bodies[1:]));write_json(a.out/'candidates.json',bodies);write_json(a.out/'excluded-overlaps.json',excluded);result=dict(status='conditional pointer leaf census only; independent decoding and native checks pending',module=module,probe_sha256=sha(a.probe/'summary.json'),compilation_targets_sha256=sha(a.probe/'compilation-targets.json'),source_db_sha256=sha(source),initial_relative_code_targets=len(locations),counts=dict(counts),candidates_sha256=sha(a.out/'candidates.json'),excluded_sha256=sha(a.out/'excluded-overlaps.json'),game_execution=False,native_game_boot=False,limitations=['Only three exact two-instruction MOV/LEA plus ordinary RET forms are inventoried; these are candidate entry interpretations, not proven function boundaries.','Initial relative code pointers can belong to mutable tables, embedded data or unused objects. No candidate is execution coverage or an implemented callback contract.','All previously recovered instructions and already compiled targets are excluded conservatively. Parent unresolved records are unchanged.','This census is not yet a compilation manifest. Independent Ghidra, exact compiler checks and native fixture validation are required before any addition.']);write_json(a.out/'summary.json',result);print(json.dumps(result),flush=True)
