"""Check the observed indirect call and tail return through the recovered native wrapper."""
import argparse,json
from pathlib import Path
from tools.cfg_recover_startup import sha,write_json
p=argparse.ArgumentParser();p.add_argument('checked',type=Path);p.add_argument('out',type=Path);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False);read=lambda p:json.loads(Path(p).read_text(encoding='utf-8'));prior=read(a.checked/'checked.json');probe=Path(prior['current_probe']);assert sha(probe/'summary.json')==sha('local/runtime/startup-v59-indirect-wrapper-repeat/summary.json');calls=[json.loads(s) for s in (probe/'native-calls.jsonl').read_text(encoding='utf-8').splitlines()];assert sha(probe/'native-calls.jsonl')==prior['current']['control_trace_sha256'];imports={r['pc']:r for r in read('local/runtime/registry-v7-memory-repeat/imports.json')};bindings={r['pc']:r for r in read('local/runtime/rwlock-contract-v1/contract.json')['bindings']};spans=[]
for index,row in enumerate(calls):
 if row['event']!='dispatch' or row['target']!=0x10207ce10:continue
 end=next(i for i in range(index+1,len(calls)) if calls[i]['event']=='dispatch-return' and calls[i]['target']==row['target']);span=calls[index:end+1];first=span[1];assert first['event']=='dispatch' and first['target']==0x10207ee90 and first['rsp']==row['rsp']-0x30;normal=next(r for r in span if r['event']=='dispatch-return' and r['target']==first['target']);assert normal['pc']==0x10207ce3a and normal['rsp']==row['rsp']-0x28;tail=next(r for r in span if r['event']=='dispatch' and r['target']==0x10207f070);assert tail['rsp']==row['rsp'];tail_return=next(r for r in span if r['event']=='dispatch-return' and r['target']==tail['target']);outer=span[-1];assert tail_return['pc']==outer['pc']==0x1020b7458 and tail_return['rsp']==outer['rsp']==row['rsp']+8 and tail_return['rax']==outer['rax']==0
 service_calls=[r for r in span if r['event']=='import'];services=[]
 for call in service_calls:
  imp=imports[call['target']];binding=bindings[call['target']];returned=next(r for r in span if r['event']=='import-return' and r['target']==call['target']);assert returned['rax']==0;services.append(dict(identity=imp,binding=binding,entry=call,returned=returned))
 assert [s['binding']['handler'] for s in services]==['mutex_lock','mutex_unlock'];spans.append(dict(first_event=index,last_event=end,events=span,native_services=services))
assert len(spans)==3;result=dict(status='three observed native indirect-call and tail-return spans checked',parent_checked_sha256=sha(a.checked/'checked.json'),trace_sha256=sha(probe/'native-calls.jsonl'),spans=spans,unresolved_call_site=0x10207ce37,unresolved_tail_site=0x10207ce59,game_aot_execution=True,original_byte_cpu_execution=False,native_game_boot=False,limitations=['The supplied straight-line wrapper and observed stack contexts associate these dispatches with its indirect call and tail jump; this covers three observed invocations only.','The mutable object table and possible other targets remain unresolved. Neither parent discovery records nor callback target sets are marked closed.','The trace omits statically compiled direct calls and individual instructions; full control coverage is not inferred.']);write_json(a.out/'checked.json',result);print(result['status'],flush=True)
