"""Compile a bounded conditional leaf set with independent decoding and native input checks."""
import argparse,json,shutil,subprocess
from pathlib import Path
from tools.cfg_recover_startup import sha,write_json
from tools.dev import ROOT,LLVM,environment
from tools.formats import ElfImage
p=argparse.ArgumentParser();p.add_argument('recovery',type=Path);p.add_argument('ghidra',type=Path);p.add_argument('out',type=Path);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False);out=a.out.resolve();env=environment();steps=[]
read=lambda p:json.loads(p.read_text(encoding='utf-8'));r=read(a.recovery/'recovery.json');assert 1<=len(r['bodies'])<=(256 if r.get('recovery_kind')=='initial-pointer-census' else 16) and sha(r['module']['path'])==r['module']['module'];assert sha(a.recovery/'input.json')==r['input_sha256'] and sha(a.recovery/'windows.json')==r['windows_sha256'];im=ElfImage(Path(r['module']['path']).read_bytes());g=read(a.ghidra/'summary.json');assert g['source_db_sha256']==r['source_db_sha256'] and g['requests_sha256']==r['windows_sha256'] and len(g['modules'])==1;gm=g['modules'][0];raw_ghidra=a.ghidra/gm['name']/'ghidra.json';assert sha(raw_ghidra)==gm['raw_sha256'];windows={w['start']:w for w in read(raw_ghidra)};leaves=[]
for b in r['bodies']:
 first=bytes.fromhex(b['instructions'][0]['bytes']);assert len(b['instructions'])==2 and b['instructions'][1]['bytes']=='c3';assert im.at_va(b['rva'],b['end']-b['rva'])==first+b'\xc3';w=windows[b['rva']];assert w['end']==b['end'] and [(i['rva'],i['length'],i['bytes']) for i in w['instructions']]==[(i['rva'],i['size'],i['bytes']) for i in b['instructions']]
 address_form=len(first)==7 and first[:3]==bytes.fromhex('488d05');assert address_form or (len(first)==3 and first[:2]==bytes.fromhex('8a47') and first[-1]<128) or (len(first)==4 and first[:3]==bytes.fromhex('488b47') and first[-1]<128);width=0 if address_form else 1 if len(first)==3 else 8;constant=b['pc']+7+int.from_bytes(first[3:],'little',signed=True) if address_form else 0
 if address_form:assert hex(constant-r['module']['logical_base'])[2:] in w['instructions'][0]['text'].lower()
 leaves.append(dict(pc=b['pc'],width=width,displacement=0 if address_form else first[-1],address=constant,return_pc=b['pc']+len(first),observed_requested_entry=b['observed_requested_entry']))
roots=[b['pc'] for b in leaves];assert roots==sorted(set(roots));assert r['observed_entry'] in roots
for name in ['input.json','recovery.json']:shutil.copyfile(a.recovery/name,out/name)
shutil.copyfile(raw_ghidra,out/'ghidra.json');header=['struct Leaf {uint64_t pc,width,displacement,address;};']+[f'extern "C" Memory* sub_{pc:x}(State*,uint64_t,Memory*);' for pc in roots];header+=['static const Leaf LEAVES[]={']+['{'+','.join(str(b[k])+'ULL' for k in ['pc','width','displacement','address'])+'},' for b in leaves]+['};',f'static constexpr size_t BATCH_COUNT={len(leaves)};','static const bb_runtime::Target BATCH_TARGETS[]={']+[f'{{{pc}ULL,sub_{pc:x}}},' for pc in roots]+['};'];(out/'leaf-batch-config.h').write_text(chr(10).join(header)+chr(10),encoding='utf-8')
def run(name,argv,code=0):
 with (out/(name+'.stdout')).open('wb') as stdout,(out/(name+'.stderr')).open('wb') as stderr:proc=subprocess.run(list(map(str,argv)),env=env,stdout=stdout,stderr=stderr,timeout=180)
 steps.append(dict(argv=list(map(str,argv)),exit_code=proc.returncode));write_json(out/'steps.json',steps);assert proc.returncode&0xffffffff==code,(name,proc.returncode)
lifter=ROOT/'build/sparse-lift-v12-memory-sources/bb-sparse-lift.exe';semantics=ROOT/'build/extended-semantics-v35-divide';inspector=ROOT/'build/control-audit-v8-memory-fp/control-audit.exe';run('lift',[lifter,out/'input.json',out/'function.bc',out/'function.ll',out/'audit.json',semantics]);run('object',[LLVM/'bin/clang.exe','-c','-O2','-march=haswell','-mno-incremental-linker-compatible',out/'function.bc','-o',out/'function.obj']);run('inspect',[inspector,out/'function.bc',out/'inspection.json']);audit=read(out/'audit.json');inspection=read(out/'inspection.json');assert audit['compiled_roots']==roots and audit['native_memory_provenance'] and not audit['missing_instruction_starts'] and not audit['unvisited_manifest_instructions'] and not audit['call_return_checks'];assert set(audit['decoded_addresses'])=={i['address'] for i in read(out/'input.json')['instructions']};ma=inspection['memory_source_audit'];assert not ma['invalid_sites'] and not ma['legacy_memory_calls'] and ma['counts']==audit['native_memory_bridges'] and not inspection['indirect_llvm_calls'];assert {int(f['name'][4:],16) for f in inspection['functions']}==set(roots);assert {int(pc,16) for pc in ma['source_pcs']}=={p for b in leaves for p in ([b['pc'],b['return_pc']] if b['width'] else [b['return_pc']])}
run('symbols',[LLVM/'bin/llvm-nm.exe','--extern-only',out/'function.obj']);symbols=(out/'symbols.stdout').read_text();defined={s.split()[-1] for s in symbols.splitlines() if len(s.split())==3};assert defined=={f'sub_{pc:x}' for pc in roots};undefined={s.split()[-1] for s in symbols.splitlines() if s.split() and s.split()[0]=='U'};assert undefined<={'__bb_sourced_read_memory_8','__bb_sourced_read_memory_64','__remill_function_return'}
objects=[out/'function.obj']
for name in ['fault','memory','control','intrinsics','fp','sourced','leaf_batch_fixture']:
 obj=out/(name+'.obj');objects.append(obj);run(name,[LLVM/'bin/clang-cl.exe','/nologo','/O2','/EHsc','/std:c++17','/DADDRESS_SIZE_BITS=64','/DHAS_FEATURE_AVX=1','/DHAS_FEATURE_AVX512=0','/clang:-mlong-double-80','/clang:-mno-avx','/clang:-mno-incremental-linker-compatible','/I'+str(ROOT/'external/remill/include'),'/I'+str(out),'/c',ROOT/'native/runtime'/(name+'.cpp'),'/Fo'+str(obj)])
run('link',[LLVM/'bin/clang-cl.exe','/nologo',*objects,'/Fe'+str(out/'fixture.exe')]);run('positive',[out/'fixture.exe','positive']);positive=read(out/'positive.stdout');assert positive['cases']==3072*len(roots) and positive['roots']==len(roots)
for n,b in enumerate(leaves):
 for mode,reason in [('unmapped',4),('guard',8)]:
  name=f'{mode}-{n}';run(name,[out/'fixture.exe',mode,str(n)],0xb0000000|reason);fault=json.loads((out/(name+'.stderr')).read_text().splitlines()[0]);assert fault['reason']==reason and int(fault['source'],16)==(b['pc'] if b['width'] else b['return_pc']) and fault['width']==(b['width'] or 8)
result=dict(status='supplemental supplied leaf compiled and native semantics checked',validation_kind='conditional-simple-leaf-batch',recovery_kind=r.get('recovery_kind','observed-pointer-sequence'),cases_per_root=3072,base_registry_identity=r['base_registry_identity'],module=r['module'],compiled_roots=roots,source_pairs=[],imports=[],instructions=2*len(roots),bytes=sum(b['end']-b['rva'] for b in r['bodies']),leaves=leaves,recovery_sha256=sha(a.recovery/'recovery.json'),ghidra_summary_sha256=sha(a.ghidra/'summary.json'),lifter_sha256=sha(lifter),semantics_sha256=sha(semantics/'amd64_avx.bc'),inspector_sha256=sha(inspector),positive=positive,negative_stops=2*len(roots),memory_bridges=ma['counts'],files={name:sha(out/name) for name in ['leaf-batch-config.h','input.json','recovery.json','ghidra.json','function.bc','function.obj','audit.json','inspection.json','symbols.stdout','positive.stdout']},native_objects={p.name:sha(p) for p in objects},game_derived_aot_execution=True,original_byte_cpu_execution=False,native_game_boot=False,limitations=r['limitations']+['Synthetic AOT checks validate the decoded bodies under authored input contexts. Only the explicitly marked observed entry has been requested by actual startup before this build.'])
write_json(out/'summary.json',result);print(json.dumps(dict(status=result['status'],roots=len(roots),cases=positive['cases'])),flush=True)
