"""Compile and independently test observed scalar-load/return native dependencies."""
import argparse,json,shutil,subprocess
from pathlib import Path
from tools.cfg_recover_startup import sha,write_json
from tools.dev import ROOT,LLVM,environment
from tools.formats import ElfImage
p=argparse.ArgumentParser();p.add_argument('recovery',type=Path);p.add_argument('ghidra',type=Path);p.add_argument('out',type=Path);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False);out=a.out.resolve();env=environment();steps=[]
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
r=read(a.recovery/'recovery.json');assert len(r['instructions'])==2 and r['instructions'][-1]['bytes']=='c3';first=bytes.fromhex(r['instructions'][0]['bytes']);address_form=len(first)==7 and first[:3]==bytes.fromhex('488d05');assert address_form or (len(first)==3 and first[:2]==bytes.fromhex('8a47')) or (len(first)==4 and first[:3]==bytes.fromhex('488b47'));width=0 if address_form else 1 if len(first)==3 else 8;displacement=0 if address_form else first[-1];assert displacement<128;pc=r['pc'];constant=(pc+len(first)+int.from_bytes(first[3:],'little',signed=True))&0xffffffffffffffff if address_form else 0;assert r['end']-r['rva']==len(first)+1;assert r['input_sha256']==sha(a.recovery/'input.json');assert r['windows_sha256']==sha(a.recovery/'windows.json');assert sha(r['module']['path'])==r['module']['module'];assert ElfImage(Path(r['module']['path']).read_bytes()).at_va(r['rva'],len(first)+1)==first+bytes.fromhex('c3')
header=[f'extern "C" Memory* sub_{pc:x}(State*,uint64_t,Memory*);',f'#define LEAF_FUNCTION sub_{pc:x}',f'static constexpr uint64_t LEAF_PC={pc}ULL,LEAF_DISPLACEMENT={displacement}ULL,LEAF_WIDTH={width}ULL,LEAF_ADDRESS={constant}ULL,LEAF_ADDRESS_FORM={int(address_form)}ULL;'];(out/'native-leaf-config.h').write_text(chr(10).join(header)+chr(10),encoding='utf-8')

g=read(a.ghidra/'summary.json');assert g['source_db_sha256']==r['source_db_sha256'] and g['requests_sha256']==r['windows_sha256'];assert g['instructions']==2 and len(g['modules'])==1;gm=g['modules'][0];assert gm['module']==r['module']['module'];assert gm['raw_sha256']==sha(a.ghidra/gm['name']/'ghidra.json');gw=read(a.ghidra/gm['name']/'ghidra.json');assert len(gw)==1 and gw[0]['start']==r['rva'] and gw[0]['end']==r['end']
assert [(i['rva'],i['length'],i['bytes']) for i in gw[0]['instructions']]==[(i['rva'],i['size'],i['bytes']) for i in r['instructions']]
if address_form:assert hex(constant-r['module']['logical_base'])[2:] in gw[0]['instructions'][0]['text'].lower()
shutil.copyfile(a.recovery/'input.json',out/'input.json');shutil.copyfile(a.recovery/'recovery.json',out/'recovery.json');shutil.copyfile(a.ghidra/gm['name']/'ghidra.json',out/'ghidra.json')
def run(name,argv,code=0):
 with (out/(name+'.stdout')).open('wb') as stdout,(out/(name+'.stderr')).open('wb') as stderr:p=subprocess.run(list(map(str,argv)),env=env,stdout=stdout,stderr=stderr,timeout=180)
 steps.append(dict(argv=list(map(str,argv)),exit_code=p.returncode));write_json(out/'steps.json',steps);assert (p.returncode&0xffffffff)==code,(name,p.returncode)
lifter=ROOT/'build/sparse-lift-v12-memory-sources/bb-sparse-lift.exe';semantics=ROOT/'build/extended-semantics-v35-divide';inspector=ROOT/'build/control-audit-v8-memory-fp/control-audit.exe';run('lift',[lifter,out/'input.json',out/'function.bc',out/'function.ll',out/'audit.json',semantics]);run('object',[LLVM/'bin/clang.exe','-c','-O2','-march=haswell','-mno-incremental-linker-compatible',out/'function.bc','-o',out/'function.obj']);run('inspect',[inspector,out/'function.bc',out/'inspection.json'])
audit=read(out/'audit.json');inspection=read(out/'inspection.json');assert audit['native_memory_provenance'] and audit['compiled_roots']==[r['pc']];assert audit['decoded_addresses']==[r['pc'],r['pc']+len(first)] and not audit['unvisited_manifest_instructions'] and not audit['missing_instruction_starts'] and not audit['call_return_checks']
ma=inspection['memory_source_audit'];assert not ma['invalid_sites'] and not ma['legacy_memory_calls'] and ma['counts']==audit['native_memory_bridges'];assert not inspection['indirect_llvm_calls'];assert {int(pc,16) for pc in ma['source_pcs']}<={r['pc'],r['pc']+len(first)};assert [f['name'] for f in inspection['functions']]==[f'sub_{pc:x}']
run('symbols',[LLVM/'bin/llvm-nm.exe','--extern-only',out/'function.obj']);symbols=(out/'symbols.stdout').read_text();defined=[s.split()[-1] for s in symbols.splitlines() if len(s.split())==3];assert defined==[f'sub_{pc:x}'];undefined=[s.split()[-1] for s in symbols.splitlines() if s.split() and s.split()[0]=='U'];assert set(undefined)<={'__bb_sourced_read_memory_8','__bb_sourced_read_memory_64','__remill_function_return','__bb_native_control_fault'}
objects=[out/'function.obj']
for name in ['fault','memory','control','intrinsics','fp','sourced','native_leaf_fixture']:
 obj=out/(name+'.obj');objects.append(obj);run(name,[LLVM/'bin/clang-cl.exe','/nologo','/O2','/EHsc','/std:c++17','/DADDRESS_SIZE_BITS=64','/DHAS_FEATURE_AVX=1','/DHAS_FEATURE_AVX512=0','/clang:-mlong-double-80','/clang:-mno-avx','/clang:-mno-incremental-linker-compatible','/I'+str(ROOT/'external/remill/include'),'/I'+str(out),'/c',ROOT/'native/runtime'/(name+'.cpp'),'/Fo'+str(obj)])
run('link',[LLVM/'bin/clang-cl.exe','/nologo',*objects,'/Fe'+str(out/'fixture.exe')]);run('positive',[out/'fixture.exe','positive']);positive=read(out/'positive.stdout');assert positive['cases']==3072 and positive['rax_result_checked'] and positive['flags_preserved']
for mode,reason in [('unmapped',4),('guard',8)]:
 run(mode,[out/'fixture.exe',mode],0xb0000000|reason);fault=json.loads((out/(mode+'.stderr')).read_text().splitlines()[0]);assert fault['reason']==reason and int(fault['source'],16)==r['pc']+(len(first) if address_form else 0) and fault['width']==(8 if address_form else width)
result=dict(status='supplemental supplied leaf compiled and native semantics checked',base_registry_identity=r['base_registry_identity'],module=r['module'],compiled_roots=[r['pc']],source_pairs=[],imports=[],instructions=2,bytes=len(first)+1,load_width=width,load_displacement=displacement,address_form=address_form,constant_address=constant,recovery_sha256=sha(a.recovery/'recovery.json'),ghidra_summary_sha256=sha(a.ghidra/'summary.json'),lifter_sha256=sha(lifter),semantics_sha256=sha(semantics/'amd64_avx.bc'),inspector_sha256=sha(inspector),positive=positive,negative_stops=2,memory_bridges=ma['counts'],undefined_symbols=undefined,files={name:sha(out/name) for name in ['native-leaf-config.h','input.json','recovery.json','ghidra.json','function.bc','function.obj','audit.json','inspection.json','symbols.stdout','positive.stdout']},native_objects={p.name:sha(p) for p in objects},game_derived_aot_execution=True,original_byte_cpu_execution=False,native_game_boot=False,limitations=['One observed scalar-load or RIP-address target and two exact instructions only. No extra function boundary, caller, callback mutation or execution closure is inferred.','Synthetic input contexts exercise the supplied AOT body independently of full startup; this is not an emulator or original-byte CPU run.','No new imports or source/target transfer pairs. The base registry and all prior uncertainty remain.'])
write_json(out/'summary.json',result);print(json.dumps(result),flush=True)
