"""Compile additive recovered CFGs after independent byte/control and boundary checks."""
import argparse,json,shutil,subprocess
from pathlib import Path
from capstone import Cs,CS_ARCH_X86,CS_MODE_64,CS_GRP_CALL,CS_GRP_JUMP
from capstone.x86_const import X86_OP_IMM
from tools.cfg_recover_startup import sha,write_json
from tools.dev import ROOT,LLVM,environment
from tools.formats import ElfImage
p=argparse.ArgumentParser();p.add_argument('recovery',type=Path);p.add_argument('ghidra',type=Path);p.add_argument('probe',type=Path);p.add_argument('out',type=Path);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False);out=a.out.resolve();read=lambda p:json.loads(Path(p).read_text(encoding='utf-8'));delta=read(a.recovery/'delta.json');assert not delta['issues'] and not delta['pending'];assert sha(a.recovery/'analysis.sqlite')==delta['delta_db_sha256'];assert sha(a.recovery/'compilation-manifest.jsonl')==delta['manifest_sha256'];assert sha(a.recovery/'windows.json')==delta['windows_sha256'];identity=read(a.recovery/'identity.json');assert sha(a.probe/'summary.json')==identity['observed_probe_sha256'];probe=read(a.probe/'summary.json');units=[json.loads(s) for s in (a.recovery/'compilation-manifest.jsonl').read_text(encoding='utf-8').splitlines()];assert 1<=len(units)<=64 and len({u['module_sha256'] for u in units})==1
module=next(m for m in read('local/runtime/registry-v7-memory-repeat/modules.json') if m['module']==units[0]['module_sha256']);base=module['logical_base'];assert sha(module['path'])==module['module'];im=ElfImage(Path(module['path']).read_bytes());g=read(a.ghidra/'summary.json');assert g['source_db_sha256']==delta['source_db_sha256'] and g['requests_sha256']==delta['windows_sha256'] and len(g['modules'])==1;gm=g['modules'][0];assert gm['module']==module['module'] and sha(a.ghidra/gm['name']/'ghidra.json')==gm['raw_sha256'];windows={r['start']:r for r in read(a.ghidra/gm['name']/'ghidra.json')};md=Cs(CS_ARCH_X86,CS_MODE_64);md.detail=True;instructions={};contracts={};roots=set();excluded=[];direct_calls=[];seen_bytes={}
for u in units:
 assert not u['issues'];w=windows[u['entry']];assert w['end']==u['fence'];expected={i['rva']:i for i in u['instructions']};actual={i['rva']:i for i in w['instructions']};assert not expected.keys()-actual.keys();roots.add(base+u['entry'])
 for edge in u['edges']:
  if edge['kind']=='annotated_control_contract_requires_runtime':
   i=expected[edge['source']];ins=next(md.disasm(bytes.fromhex(i['bytes']),i['rva'],count=1));assert ins.group(CS_GRP_CALL) and ins.operands[0].type==X86_OP_IMM and ins.operands[0].imm==edge['target'];provenance=dict(source_db_sha256=delta['delta_db_sha256'],module=module['module'],entry=u['entry'],source=i['rva'],bytes=i['bytes'],size=i['size'],target_module=edge['target_module'],target=edge['target'],detail=edge['detail'],kind=edge['kind']);contracts[base+i['rva']]=dict(address=base+i['rva'],expected_next_pc=base+i['rva']+i['size'],kind='no-normal-return',provenance=json.dumps(provenance,sort_keys=True,separators=(',',':')))
 for at in actual.keys()-expected.keys():
  # This narrow exception requires the established exact failure-call annotation.
  matches=[e for e in u['edges'] if e['kind']=='annotated_control_contract_requires_runtime' and e['detail']=='stack-protector-failure' and e['source']+expected[e['source']]['size']==at];assert len(matches)==1 and actual[at]['bytes']=='90' and at+1 in expected;excluded.append(dict(module=module['module'],rva=at,ghidra=actual[at],conditional_nonreturn=matches[0],reason='One NOP on the linear continuation of the exact annotated failure call; excluded only under its explicit nonreturn contract.'))
 for at,i in expected.items():
  gi=actual[at];raw=bytes.fromhex(i['bytes']);assert gi['length']==i['size']==len(raw) and gi['bytes']==i['bytes'] and im.at_va(at,len(raw))==raw;ins=next(md.disasm(raw,at,count=1));assert ins.size==len(raw)
  if ins.group(CS_GRP_CALL) or ins.group(CS_GRP_JUMP):
   immediate=ins.operands[0].imm if ins.operands[0].type==X86_OP_IMM else None
   if immediate is not None:assert gi['targets']==[immediate]
   else:assert not gi['targets']
   if ins.group(CS_GRP_CALL) and immediate is not None:
    direct_calls.append(dict(source=base+at,target=base+immediate));
    if immediate in expected:roots.add(base+immediate)
  for byte in range(at,at+len(raw)):
   assert byte not in seen_bytes or seen_bytes[byte]==at;seen_bytes[byte]=at
  row=dict(address=base+at,bytes=i['bytes']);assert base+at not in instructions or instructions[base+at]==row;instructions[base+at]=row
assert delta['observed_entry'] in roots;known={r['pc'] for r in read(a.probe/'compilation-targets.json')+read('local/runtime/registry-v7-memory-repeat/imports.json')};assert not roots&known;assert all(call['target'] in roots|known for call in direct_calls)
data=dict(native_memory_provenance=True,roots=sorted(roots),instructions=[instructions[pc] for pc in sorted(instructions)],return_contracts=[contracts[pc] for pc in sorted(contracts)]);write_json(out/'input.json',data);write_json(out/'independent.json',dict(ghidra_summary_sha256=sha(a.ghidra/'summary.json'),excluded_linear_continuations=excluded,direct_calls=direct_calls));shutil.copyfile(a.recovery/'delta.json',out/'recovery.json');shutil.copyfile(a.recovery/'compilation-manifest.jsonl',out/'units.jsonl');shutil.copyfile(a.ghidra/gm['name']/'ghidra.json',out/'ghidra.json');env=environment();steps=[]
def run(name,argv):
 with (out/(name+'.stdout')).open('wb') as stdout,(out/(name+'.stderr')).open('wb') as stderr:r=subprocess.run(list(map(str,argv)),env=env,stdout=stdout,stderr=stderr,timeout=180)
 steps.append(dict(argv=list(map(str,argv)),exit_code=r.returncode));write_json(out/'steps.json',steps);assert r.returncode==0,(name,r.returncode)
lifter=ROOT/'build/sparse-lift-v12-memory-sources/bb-sparse-lift.exe';semantics=ROOT/'build/extended-semantics-v35-divide';inspector=ROOT/'build/control-audit-v8-memory-fp/control-audit.exe';run('lift',[lifter,out/'input.json',out/'function.bc',out/'function.ll',out/'audit.json',semantics]);run('object',[LLVM/'bin/clang.exe','-c','-O2','-march=haswell','-mno-incremental-linker-compatible',out/'function.bc','-o',out/'function.obj']);run('inspect',[inspector,out/'function.bc',out/'inspection.json']);audit=read(out/'audit.json');inspection=read(out/'inspection.json');assert audit['compiled_roots']==data['roots'] and audit['native_memory_provenance'];assert set(audit['decoded_addresses'])==set(instructions) and not audit['unvisited_manifest_instructions'];assert set(audit['missing_instruction_starts'])<={r['expected_next_pc'] for r in contracts.values()};assert {row['source'] for row in audit['call_return_checks'] if row['no_normal_return']}==set(contracts)
for row in audit['call_return_checks']:
 if row['no_normal_return']:assert row['provenance']==contracts[row['source']]['provenance'] and row['expected_next_pc']==contracts[row['source']]['expected_next_pc']
transfers=[s for s in inspection['sites'] if s['callee']=='__bb_native_block_transfer'];assert all(not site['cfg_reachable_from_entry'] and site['nounwind'] for site in transfers);assert {int(site['arguments'][4]['value_hex'],16) for site in transfers}==set(audit['missing_instruction_starts'])
guards={(g['root'],g['source']):g for g in audit['call_return_checks']}
for site in inspection['sites']:
 if site['callee']!='__bb_native_control_fault':continue
 args=site['arguments'];assert site['noreturn'] and site['nounwind'] and len(args)==6;source=int(args[1]['value_hex'],16);guard=guards[site['function'],source];assert int(args[4]['value_hex'],16)==guard['expected_next_pc'];assert int(args[3]['value_hex'],16)==(2 if guard['no_normal_return'] else 1)
ma=inspection['memory_source_audit'];assert not ma['invalid_sites'] and not ma['legacy_memory_calls'] and ma['counts']==audit['native_memory_bridges'] and not inspection['indirect_llvm_calls'];assert {int(pc,16) for pc in ma['source_pcs']}<=set(instructions);assert {int(f['name'][4:],16) for f in inspection['functions']}==roots
run('symbols',[LLVM/'bin/llvm-nm.exe','--extern-only',out/'function.obj']);symbols=(out/'symbols.stdout').read_text();defined={s.split()[-1] for s in symbols.splitlines() if len(s.split())==3};assert defined=={f'sub_{pc:x}' for pc in roots};undefined={s.split()[-1] for s in symbols.splitlines() if s.split() and s.split()[0]=='U'};assert all(int(s[4:],16) in known for s in undefined if s.startswith('sub_'));assert not {'__remill_error','__remill_missing_block','__bb_native_block_transfer'}&undefined
result=dict(status='supplied CFG compiled with independently checked boundaries',validation_kind='independent-cfg-compilation',base_registry_identity=probe['registry_identity'],module=module,compiled_roots=sorted(roots),source_pairs=[],imports=[],instructions=len(instructions),bytes=len(seen_bytes),conditional_entries=[dict(pc=pc,observed_requested_entry=pc==delta['observed_entry']) for pc in sorted(roots)],lifter_sha256=sha(lifter),semantics_sha256=sha(semantics/'amd64_avx.bc'),inspector_sha256=sha(inspector),recovery_sha256=sha(a.recovery/'delta.json'),source_db_sha256=delta['delta_db_sha256'],parent_source_db_sha256=delta['source_db_sha256'],unreachable_missing_blocks=audit['missing_instruction_starts'],reachable_block_transfers=0,nonreturn_contracts=len(contracts),call_return_checks=len(audit['call_return_checks']),memory_bridges=ma['counts'],undefined_symbols=sorted(undefined),files={name:sha(out/name) for name in ['input.json','independent.json','recovery.json','units.jsonl','ghidra.json','function.bc','function.obj','audit.json','inspection.json','symbols.stdout']},native_objects={},game_derived_aot_execution=False,original_byte_cpu_execution=False,native_game_boot=False,limitations=delta['limitations']+['This is static CFG compilation with the established compiler and runtime contracts. It is not exhaustive function semantics or execution coverage; native startup execution remains a separate gate.','One independently decoded NOP is excluded only under an existing exact failure-call nonreturn annotation. Unknown nonlocal destinations remain unresolved.']);write_json(out/'summary.json',result);print(json.dumps(dict(status=result['status'],roots=len(roots),instructions=len(instructions),nonreturn_contracts=len(contracts))),flush=True)
