"""Check supplied direct-memory ABI sites and define an explicit native pool profile."""
import argparse,json,sqlite3
from pathlib import Path
from capstone import Cs,CS_ARCH_X86,CS_MODE_64
from tools.cfg_recover_startup import sha,write_json
from tools.formats import ElfImage
p=argparse.ArgumentParser();p.add_argument('out',type=Path);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False)
read=lambda p:json.loads(Path(p).read_text(encoding='utf-8'));old=Path('local/runtime/mutex-contract-v1');contract=read(old/'contract.json');imports=read('local/runtime/registry-v7-memory-repeat/imports.json');db=sqlite3.connect(Path('local/cfg/startup-recovery-v31-conditional-repeat/analysis.sqlite').resolve().as_uri()+'?mode=ro',uri=True);h,path=db.execute('select hash,path from module where name=?',('eboot.bin',)).fetchone();assert sha(path)==h;im=ElfImage(Path(path).read_bytes());decoder=Cs(CS_ARCH_X86,CS_MODE_64);checked=[]
for window in read('local/cfg/ghidra-startup-dmem-v1/eboot.bin/ghidra.json'):
 for row in window['instructions']:
  raw=im.at_va(row['rva'],row['length']);assert raw.hex()==row['bytes'];ins=next(decoder.disasm(raw,row['rva'],count=1));assert ins.size==row['length'];checked.append(dict(**row,capstone=ins.mnemonic+' '+ins.op_str))
by={r['rva']:r for r in checked}
for at,code in [(0x2081a89,'bf00000000'),(0x2081a8e,'ba00004007'),(0x2081a93,'b900002000'),(0x2081a98,'4531c0'),(0x2081a9b,'4889c6'),(0x2081aa7,'4c8b45c8'),(0x2081ab4,'ba03000000'),(0x2081ab9,'31c9'),(0x2081abb,'41b900002000')]:assert by[at]['bytes']==code
for at,target in [(0x2081a80,0x2bbeaa8),(0x2081a9e,0x2bbeab8),(0x2081ac1,0x2bbeac8),(0x2081ad7,0x2bbead8),(0x2081ea4,0x2bbeaa8),(0x2081ebc,0x2bbeab8),(0x2081ee9,0x2bbeac8),(0x2081f00,0x2bbead8)]:assert by[at]['targets']==[target]
services={'pO96TwzOm5E':'direct_memory_size','rTXw65xmLIA':'direct_memory_allocate','L-Q3LEjIbgA':'direct_memory_map','MBuItvba6z8':'direct_memory_release'};bindings=contract['bindings'][:]
for nid,handler in services.items():
 canonical=next(r for r in imports if r.get('canonical') and r['nid']==nid and r['library']==r['module']=='libkernel');assert canonical['library_version']==1 and canonical['module_version']==257 and not canonical['compiled_export']
 for imp in imports:
  if imp['pc']==canonical['pc'] or imp.get('canonical_service_pc')==canonical['pc']:
   assert imp['nid']==nid and imp['library']==imp['module']=='libkernel' and not imp['compiled_export'];bindings.append(dict(pc=imp['pc'],canonical_pc=canonical['pc'],handler=handler,nid=nid,library='libkernel',library_version=1,module='libkernel',module_version=257))
bindings.sort(key=lambda r:r['pc']);assert len(bindings)==len({r['pc'] for r in bindings});one=read('local/runtime/direct-memory-v1/summary.json');two=read('local/runtime/direct-memory-v2-repeat/summary.json');assert one==two and two['positive']['aot_service_calls']==4302;regression=read('local/runtime/memory-v8-dynamic-regression/summary.json');assert regression['positive']['cases']==49256
contract.update(status='bounded native direct-memory service interface checked',parent_contract_sha256=sha(old/'contract.json'),bindings=bindings,direct_memory_services=True,direct_memory_budget=0x120000000,direct_map_range=[0x1000000000,0x8000000000],direct_page_size=0x4000,direct_profile='Explicit native 4.5 GiB reserved pool; backing committed per successful allocation. This is a chosen native compatibility profile, not a measured PS4 capacity.',first_allocation=dict(length=0x7400000,alignment=0x200000,memory_type=0,protection=3,map_flags=0,address_hint=0),checked_direct_instructions=len(checked),direct_ghidra_sha256=sha('local/cfg/ghidra-startup-dmem-v1/eboot.bin/ghidra.json'),direct_authored_sha256=sha('local/runtime/direct-memory-v2-repeat/summary.json'),memory_regression_sha256=sha('local/runtime/memory-v8-dynamic-regression/summary.json'),direct_references=['https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc','https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualfree'],baseline_reference_sha256={str(p):sha(p) for p in map(Path,['external/shadPS4/src/core/libraries/kernel/memory.cpp','external/shadPS4/src/core/memory.cpp','external/shadPS4/src/core/libraries/kernel/memory.h'])})
contract['limitations']+=['Only memory type zero, power-of-two page alignment, zero-hint flags-zero RW maps, and exact unmapped allocation release are implemented. Other types/protections/flags/hints, partial/mapped release and unmapping stop explicitly.','The native reserved pool is a budget and backing identity; reservation does not commit or touch 4.5 GiB. Query returns that real pool budget as a 64-bit value.','Logical mappings share the allocated private backing, stay NX, and never replace initial module mappings or unresolved guards.','GPU ownership/coherence, flexible memory and full process memory behavior remain open.']
write_json(a.out/'checked-instructions.json',checked);write_json(a.out/'contract.json',contract);print(json.dumps(dict(status=contract['status'],bindings=len(bindings),instructions=len(checked),budget=contract['direct_memory_budget'])),flush=True)
