"""Validate exact canary provider identities and independently decoded pointer/value reads."""
import argparse,json
from pathlib import Path
from tools.cfg_recover_startup import sha,write_json
p=argparse.ArgumentParser();p.add_argument('out',type=Path);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False)
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
scan=Path('local/runtime/canary-scan-v2-gaps');ghidra=Path('local/cfg/ghidra-canary-reads-v1');uses=read(scan/'uses.json');names={r['module']:r['name'] for r in uses};checked=[]
for prefix in read(scan/'selected-prefixes.json'):
 windows=read(ghidra/names[prefix['module']]/'ghidra.json');window=next(r for r in windows if r['start']==prefix['start'] and r['end']==prefix['end']);assert [r['rva'] for r in window['instructions']]==[r['rva'] for r in prefix['prefix']]
 for one,two in zip(window['instructions'],prefix['prefix'],strict=True):assert one['bytes']==two['bytes'] and one['length']==len(bytes.fromhex(two['bytes']))
 pointer=window['instructions'][0];value=next(r for r in window['instructions'] if r['rva']==prefix['read_rva']);assert 'qword ptr' in pointer['text'] and 'qword ptr' in value['text'];assert f"0x{prefix['slot']:08x}" in pointer['text'];checked.append(dict(prefix=prefix,ghidra_instructions=window['instructions']))
entry=read(Path('local/cfg/ghidra-startup-entry-v1/libc.prx/ghidra.json'));atexit=next(r for r in entry if r['start']==0x2f110);by_rva={r['rva']:r for r in atexit['instructions']}
for at,code in [(0x2f119,'488b1dc0930800'),(0x2f120,'488b03'),(0x2f123,'488945f0'),(0x2f14b,'488b0b'),(0x2f14e,'483b4df0'),(0x2f152,'7507'),(0x2f15b,'e8b00ffdff')]:assert by_rva[at]['bytes']==code
assert by_rva[0x2f152]['targets']==[0x2f15b] and by_rva[0x2f15b]['targets']==[0x110]
imports=read(Path('local/runtime/registry-v7-memory-repeat/imports.json'));failure=next(r for r in imports if r['pc']==0x800000110);assert failure['nid']=='Ou3iL1abvng' and failure['library']==failure['module']=='libkernel' and not failure['compiled_export']
contract=dict(status='bounded native canary data interface independently checked',nid='f7uOxY9mM1U',library='libkernel',library_version=1,module='libkernel',module_version=257,object_size=8,logical_address=0x70000400000,rights=3,scope='one process-owned opaque canary word shared by exact-identity imports',initialization='native OS entropy before protected guest frames; an explicit recorded replay seed is allowed for experiments',mutability='registered writes remain possible; changing the word while a protected frame is active must take its supplied failure path',failure_gateway=failure,uses=uses,checked_prefixes=checked,recovered_slot_references=read(scan/'summary.json')['slot_references'],missing_recovered_prefixes=read(scan/'summary.json')['missing_recovered_prefixes'],source_db_sha256=read(scan/'summary.json')['source_db_sha256'],primary_reference=dict(url='https://lists.llvm.org/pipermail/libc-commits/2024-January/020237.html',scope='LLVM libc documents a pointer-sized global canary initialized from an OS random source for targets not using a TLS canary. This supports a native implementation pattern, not a PS4 seed or complete console ABI.'),limitations=['Symbol size is zero; supplied decoded loads and save/compare behavior support this eight-byte native interface.','Five bundled modules have no recovered read prefix in this startup set; exact namespace/version matches identify the same provider, but no execution/body claim is made for those modules.','Unknown indirect writes, wider reads and dynamic interposition are not proven absent. Wider accesses outside the eight-byte native object must stop.','No PS4 random value, seed distribution or memory-protection policy is claimed.','The stack-check failure gateway remains an explicit unimplemented process stop. No success stub bypasses mismatches.'],game_aot_execution=False)
write_json(a.out/'contract.json',contract);print(json.dumps(dict(status=contract['status'],uses=len(uses),checked_prefixes=len(checked),recovered_slot_references=contract['recovered_slot_references'],missing_recovered_prefixes=contract['missing_recovered_prefixes'])),flush=True)
