"""Bind a bounded main-module static TLS and FS self-pointer initialization contract."""
import argparse,json
from pathlib import Path
from tools.cfg_recover_startup import sha,write_json
p=argparse.ArgumentParser();p.add_argument('out',type=Path);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False)
read=lambda p:json.loads(Path(p).read_text(encoding='utf-8'));scan=read('local/runtime/tls-scan-v1/summary.json');one=read('local/runtime/main-tls-v2-name/summary.json');two=read('local/runtime/main-tls-v3-repeat/summary.json');assert one==two and two['positive']['aot_calls']==3752 and two['negative_stops']==3;assert scan['fs_self_loads']==scan['immediate_offset_uses']==328 and not scan['unknown_followups'];assert sha(scan['module_path'])==scan['module'];assert scan['tls']['memory_size']==1872 and scan['tls']['file_size']==0 and scan['tls']['alignment']==16
for name,digest in scan['files'].items():assert sha(Path('local/runtime/tls-scan-v1')/name)==digest
for name,digest in two['objects'].items():assert sha(Path('local/runtime/main-tls-v2-name')/name)==sha(Path('local/runtime/main-tls-v3-repeat')/name)==digest
contract=dict(status='bounded native main initial-exec TLS interface checked',registry_identity=sha('local/runtime/registry-v7-memory-repeat/identity.json'),loader_plan_sha256=sha('local/runtime/loader-plan-v9-runtime-word/summary.json'),module=scan['module'],module_path=scan['module_path'],tcb=0x74000010000,memory_size=1872,file_size=0,alignment=16,initial_hex='',tcb_supported_bytes=8,tcb_guarded_bytes=56,scan_sha256=sha('local/runtime/tls-scan-v1/summary.json'),authored_sha256=sha('local/runtime/main-tls-v3-repeat/summary.json'),requires_before_entry=True,initial_fs_base=0,first_use=scan['first_use'],source_fs_loads=328,distinct_offsets=scan['distinct_offsets'],ghidra_sha256=scan['ghidra_sha256'],references=scan['references'],game_execution=False,limitations=['Main PT_TLS occupies the 1872 bytes immediately below the chosen native TCB address; the first eight TCB bytes hold its logical self pointer.','Remaining 56 bytes in the explicitly reserved TCB envelope are guarded, not supplied as guessed DTV/thread/fiber fields. The envelope size is a native compatibility reservation.','Only explicit State FS base changes; Windows host FS is never modified.','Dynamic module TLS, DTV, symbol/module-index relocations, guest thread creation and complete startup ABI remain open. All 29 prior guards remain.','The ten checked offset words are initial mutable data, not immutable constants or execution coverage.'])
write_json(a.out/'contract.json',contract);print('Main static TLS initialization contract checked')
