"""Verify authored call-return evidence and publish the current compiler checkpoint."""
import argparse,json
from pathlib import Path
from tools.cfg_recover_startup import sha,write_json
p=argparse.ArgumentParser();p.add_argument('out',type=Path);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False);base=Path('local/compiler-spike')
def read(p):return json.loads(p.read_text(encoding='utf-8'))
old=base/'call-return-characterize-v1';first=base/'call-return-checks-v3-exact';repeat=base/'call-return-checks-v4-repeat';inputs=base/'call-return-inputs-v2-exact';ghidra=base/'call-return-ghidra-v1'
legacy=read(old/'summary.json');checked=read(repeat/'summary.json');assert legacy['result']['legacy_wrong_continuations']==4096 and legacy['result']['legacy_ignored_nonreturn_contracts']==4096;assert checked['result']['cases']==14336 and checked['result']['native_faults']==8192
repeated={name:sha(first/name) for name in ['input.json','specs.json','authored.s','audit.json','function.bc','function.obj','execute.stdout']};assert all(sha(repeat/name)==value for name,value in repeated.items())
checks=read(inputs/'summary.json');assert checks['accepted']==2 and checks['rejected']==12;independent=read(ghidra/'summary.json');assert len(independent['instructions'])==3
compiler=Path('build/sparse-lift-v10-exact-read');identity=read(compiler/'identity.json');assert sha(compiler/'bb-sparse-lift.exe')==checked['lifter_sha256']==identity['executable_sha256'];assert sha('external/remill/lib/BC/TraceLifter.cpp')==identity['original_trace_source_sha256'];assert sha('native/sparse_lift/main.cpp')==identity['driver_source_sha256']
summary=dict(status='authored ordinary call-return guards and exact instruction reads validated; not yet applied to game object set',legacy=legacy,checked=checked,inputs=checks,ghidra=independent,repeated_artifact_sha256=repeated,compiler_identity=identity,active_objects_unchanged='local/compiler-spike/divide-integration-manifest-v1/active-objects.json',active_manifest_sha256=sha(base/'divide-integration-manifest-v1/active-objects.json'),ordinary_calls_previously_unchecked=True,pinned_check_call_return_scope='asynchronous hypercalls only',fault_abi='noreturn nounwind C void __bb_native_control_fault(State*, uint64_t source, Memory*, uint32_t reason, uint64_t wanted, uint64_t actual)',fault_reasons={'1':'ordinary callee returned with unexpected logical PC','2':'ordinary return violates exact declared nonreturn assertion'},limitations=['Authored static assembly and native AOT only; no game CPU execution.','Fixture escape bridge is not production native/guest unwind.','4,305 exact recovery nonreturn annotations still require migration into compiler inputs; conditional evidence is not a global callee attribute.','Missing-block source/reason, native handling and complete linkage remain open.'],p3_gate_passed=False,native_game_boot=False)
write_json(a.out/'checked.json',summary);write_json(Path('reports/call-return-evidence.json'),summary);print(json.dumps(dict(status=summary['status'],cases=14336,explicit_faults=8192,input_checks=14,repeat=True)),flush=True)
